import { FullWeatherData, GeoLocation } from './types';

export const DEFAULT_CITY: GeoLocation = {
  id: 681290,
  name: 'Craiova',
  latitude: 44.3302,
  longitude: 23.7949,
  country: 'România',
  admin1: 'Dolj',
  timezone: 'Europe/Bucharest',
};

export const POPULAR_CITIES: GeoLocation[] = [
  { id: 681290, name: 'Craiova', latitude: 44.3302, longitude: 23.7949, country: 'România', admin1: 'Dolj' },
  { id: 683506, name: 'București', latitude: 44.4323, longitude: 26.1063, country: 'România', admin1: 'București' },
  { id: 681290, name: 'Cluj-Napoca', latitude: 46.7712, longitude: 23.6236, country: 'România', admin1: 'Cluj' },
  { id: 665087, name: 'Timișoara', latitude: 45.7537, longitude: 21.2257, country: 'România', admin1: 'Timiș' },
  { id: 675810, name: 'Iași', latitude: 47.1585, longitude: 27.6014, country: 'România', admin1: 'Iași' },
  { id: 683844, name: 'Brașov', latitude: 45.6486, longitude: 25.6061, country: 'România', admin1: 'Brașov' },
  { id: 680963, name: 'Constanța', latitude: 44.1807, longitude: 28.6343, country: 'România', admin1: 'Constanța' },
];

export const MOCK_WEATHER_CRAIOVA: FullWeatherData = {
  location: DEFAULT_CITY,
  lastUpdated: new Date().toLocaleTimeString('ro-RO', { hour: '2-digit', minute: '2-digit' }),
  current: {
    time: new Date().toISOString(),
    temperature: 22.4,
    apparentTemperature: 21.8,
    isDay: 1,
    weatherCode: 1,
    relativeHumidity: 48,
    precipitation: 0.0,
    rain: 0.0,
    showers: 0.0,
    snowfall: 0.0,
    cloudCover: 15,
    pressure: 1018.4,
    windSpeed: 11.2,
    windDirection: 75,
    windGusts: 18.5,
  },
  hourly: Array.from({ length: 24 }).map((_, i) => {
    const hour = (new Date().getHours() + i) % 24;
    const isDay = hour >= 6 && hour <= 21;
    const tempBase = 22 - Math.abs(14 - hour) * 0.8;
    return {
      time: `${hour.toString().padStart(2, '0')}:00`,
      temperature: Math.round(tempBase * 10) / 10,
      apparentTemperature: Math.round((tempBase - 0.5) * 10) / 10,
      precipitationProbability: (i % 6) * 5,
      precipitation: 0,
      weatherCode: isDay ? 1 : 0,
      pressure: 1018 + (i % 3) * 0.4,
      visibility: 10.0,
      windSpeed: 9 + (i % 5),
      uvIndex: isDay ? Math.max(0, 7 - Math.abs(13 - hour)) : 0,
    };
  }),
  daily: [
    {
      date: 'Luni',
      weatherCode: 1,
      temperatureMax: 24.5,
      temperatureMin: 12.0,
      apparentTemperatureMax: 24.0,
      apparentTemperatureMin: 11.5,
      sunrise: '05:42',
      sunset: '20:56',
      uvIndexMax: 6.8,
      precipitationSum: 0.0,
      precipitationProbabilityMax: 5,
      windSpeedMax: 14.5,
    },
    {
      date: 'Marți',
      weatherCode: 2,
      temperatureMax: 25.8,
      temperatureMin: 13.5,
      apparentTemperatureMax: 25.2,
      apparentTemperatureMin: 13.0,
      sunrise: '05:41',
      sunset: '20:57',
      uvIndexMax: 7.1,
      precipitationSum: 0.2,
      precipitationProbabilityMax: 15,
      windSpeedMax: 12.0,
    },
    {
      date: 'Miercuri',
      weatherCode: 61,
      temperatureMax: 21.2,
      temperatureMin: 14.0,
      apparentTemperatureMax: 20.8,
      apparentTemperatureMin: 13.8,
      sunrise: '05:40',
      sunset: '20:58',
      uvIndexMax: 4.5,
      precipitationSum: 3.5,
      precipitationProbabilityMax: 65,
      windSpeedMax: 19.8,
    },
    {
      date: 'Joi',
      weatherCode: 2,
      temperatureMax: 23.4,
      temperatureMin: 12.8,
      apparentTemperatureMax: 22.9,
      apparentTemperatureMin: 12.0,
      sunrise: '05:39',
      sunset: '20:59',
      uvIndexMax: 6.2,
      precipitationSum: 0.5,
      precipitationProbabilityMax: 20,
      windSpeedMax: 13.5,
    },
    {
      date: 'Vineri',
      weatherCode: 0,
      temperatureMax: 26.2,
      temperatureMin: 14.2,
      apparentTemperatureMax: 26.0,
      apparentTemperatureMin: 14.0,
      sunrise: '05:38',
      sunset: '21:00',
      uvIndexMax: 7.5,
      precipitationSum: 0.0,
      precipitationProbabilityMax: 0,
      windSpeedMax: 11.0,
    },
    {
      date: 'Sâmbătă',
      weatherCode: 1,
      temperatureMax: 27.5,
      temperatureMin: 15.6,
      apparentTemperatureMax: 27.2,
      apparentTemperatureMin: 15.0,
      sunrise: '05:37',
      sunset: '21:01',
      uvIndexMax: 7.8,
      precipitationSum: 0.0,
      precipitationProbabilityMax: 5,
      windSpeedMax: 10.5,
    },
    {
      date: 'Duminică',
      weatherCode: 80,
      temperatureMax: 24.8,
      temperatureMin: 15.0,
      apparentTemperatureMax: 24.5,
      apparentTemperatureMin: 14.8,
      sunrise: '05:36',
      sunset: '21:02',
      uvIndexMax: 5.9,
      precipitationSum: 1.8,
      precipitationProbabilityMax: 40,
      windSpeedMax: 16.0,
    },
  ],
  airQuality: {
    europeanAqi: 22,
    usAqi: 38,
    pm10: 16.4,
    pm2_5: 9.2,
    carbonMonoxide: 240,
    nitrogenDioxide: 18.5,
    sulphurDioxide: 3.2,
    ozone: 54.0,
  },
};
